package com.hmdp.ai.runtime;

public enum ConversationEventType {
    USER_INPUT, REWRITE, ROUTE_DECISION, CONSTRAINT_EXTRACTED, SEMANTIC_INTERPRETATION, STATE_REDUCED,
    POLICY_DECISION, LOCATION_RESOLUTION, DECISION_STARTED, RETRIEVAL,
    RESULT_EVALUATION, AUTO_RELAXATION, TOOL_CALL, TOOL_RESULT, ASSISTANT_OUTPUT,
    STALE_RUNTIME_RESULT, ERROR
}
